import React from "react";
import { PeopleFill, ArrowUp, ArrowDown } from "react-bootstrap-icons";
import "bootstrap/dist/css/bootstrap.min.css";

const VisitorLiveLogs = () => {
  return (
    <div className="container-fluid mt-4">
      <div className="ticket-log-wrapper p-4 rounded">
        <h4 className="text-warning fw-bold mb-3">
          Live Customer's Ticket Logs
        </h4>
        {/* Table Header */}
        <div className="bg-white rounded px-3 py-3 overflow-auto">
          <div className="row align-items-center fw-semibold text-dark flex-nowrap m-0">
            <div className="col-1 text-nowrap">#</div>
            <div className="col-2 text-nowrap">Ticket For</div>
            <div className="col-2 text-nowrap">Customer</div>
            <div className="col-2 text-nowrap">Mobile no.</div>
            <div className="col-1 d-flex align-items-center gap-1 text-primary text-nowrap">
              <PeopleFill size={18} />
              Members
            </div>
            <div className="col-2 d-flex align-items-center gap-1 text-primary text-nowrap">
              <ArrowUp size={18} />
              Entry DateTime
            </div>
            <div className="col-2 d-flex align-items-center gap-1 text-danger text-nowrap">
              <ArrowDown size={18} />
              Exit DateTime
            </div>
            {/* Auto-width column */}
            <div className="col text-end text-nowrap">
              Ticket Generated by
            </div>

          </div>
        </div>

      </div>
    </div>
  );
};

export default VisitorLiveLogs;
